version: '3'
services:


    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
        container_name: "${APP_NAME}-elastic"
        environment:
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - elastic_volume:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - laravel_elastic_net

    database:
        env_file:
            - .env
        image: mysql:5.7
        container_name: "${APP_NAME}-db"
        restart: always
        expose:
            - ${PORT_DB}
        networks:
            - laravel_elastic_net
        volumes:
            - laravel_elastic_db:/var/lib/mysql
            - laravel_elastic_db_settings:/etc/mysql/conf.d

    phpmyadmin:
        env_file:
            - .env
        image: phpmyadmin/phpmyadmin
        container_name: "${APP_NAME}-phpmyadmin"
        expose:
            - ${PORT_PHPMYADMIN}
        networks:
            - laravel_elastic_net
        restart: always
        depends_on:
            - database

    php:
        environment:
            - DEVELOPMENT=${DEVELOPMENT}
        build:
            context: ./php-dev
            dockerfile: Dockerfile
        container_name: "${APP_NAME}-php"
        ports:
            - ${LOCAL_IP_ADDRESS}:${PORT_PHP}:9000
        networks:
            - laravel_elastic_net
        depends_on:
            - database
        volumes:
            - ./../elastic_app:/var/www/html
            - /var/www/html/.docker
        restart: always

    web:
        env_file:
            - .env
        image: nginx
        container_name: "${APP_NAME}-web"
        ports:
            - ${LOCAL_IP_ADDRESS}:${PORT_HTTP}:${PORT_HTTP}
            - ${LOCAL_IP_ADDRESS}:${PORT_HTTPS}:${PORT_HTTPS}
        networks:
            - laravel_elastic_net
        restart: always
        depends_on:
            - php
        volumes:
            - ./../elastic_app:/var/www/html
            - /var/www/html/.docker
            - ./nginx/vhosts:/etc/nginx/vhost.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/pass:/etc/nginx/pass
            - ./nginx/ssl:/etc/nginx/ssl

volumes:
    laravel_elastic_db: {}
    laravel_elastic_db_settings: {}
    elastic_volume: {}

networks:
    laravel_elastic_net:
